version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 864899837235.dkr.ecr.ap-south-1.amazonaws.com

  build:
    commands:
      - echo Building the Docker image...
      - docker build -t abhinay/mywebsite .
      - docker tag abhinay/mywebsite:0.2 864899837235.dkr.ecr.ap-south-1.amazonaws.com/accordion/abhinay

  post_build:
    commands:
      - echo Pushing the Docker image to ECR...
      - docker push 864899837235.dkr.ecr.ap-south-1.amazonaws.com/accordion/abhinay:0.2

artifacts:
  files: appspec.yml
